#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/libarchive-config
scripts/libarchive-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/libmysofa-config
scripts/libmysofa-build "$@"
scripts/shaderc-config
scripts/shaderc-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
