#!/bin/sh
set -e
export LC_ALL=C

scripts/fribidi-config
scripts/fribidi-build "$@"
scripts/freetype2-config
scripts/freetype2-build "$@"
scripts/harfbuzz-config
scripts/harfbuzz-build "$@"
scripts/libarchive-config
scripts/libarchive-build "$@"
scripts/dav1d-config
scripts/dav1d-build "$@"
scripts/libunibreak-config
scripts/libunibreak-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/libmysofa-config
scripts/libmysofa-build "$@"
scripts/avisynth-config
scripts/avisynth-build "$@"
scripts/shaderc-config
scripts/shaderc-build "$@"
scripts/libaom-config
scripts/libaom-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
