#!/bin/sh
export LC_ALL=C

scripts/ffmpeg-clean
#scripts/fribidi-clean
scripts/shaderc-clean
scripts/libplacebo-clean
scripts/libarchive-clean
scripts/libass-clean
scripts/libmysofa-clean
scripts/mpv-clean
rm -rf build_libs
