#!/bin/sh
export LC_ALL=C

scripts/ffmpeg-clean
scripts/freetype2-clean
scripts/fribidi-clean
scripts/harfbuzz-clean
scripts/shaderc-clean
scripts/libaom-clean
scripts/libplacebo-clean
scripts/libarchive-clean
scripts/dav1d-clean
scripts/libunibreak-clean
scripts/libass-clean
scripts/libmysofa-clean
scripts/avisynth-clean
scripts/mpv-clean
rm -rf build_libs
