#!/bin/sh
set -e
BUILD="$(pwd)"

OPTIONS="$@"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/avisynth/avs_core
cmake -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DHEADERS_ONLY:bool=on -DCMAKE_BUILD_TYPE=Debug ..

