#!/bin/sh
set -e
BUILD="$(pwd)"

OPTIONS="$@"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/avisynth/avs_core
cmake -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DBUILD_SHARED_LIBS=OFF -DENABLE_PLUGINS=OFF -DHEADERS_ONLY:bool=off -DCMAKE_BUILD_TYPE=Release ..

