#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/curl_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/curl_options) "$@"
    unset -v IFS
fi

OPTIONS="--enable-static --disable-shared --with-openssl"
if "$BUILD"/scripts/test-libmpv ; then
    OPTIONS="$OPTIONS --with-pic"
fi

echo "Using the following options: $OPTIONS $@"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/curl
# Later curl doesn't automatically run configure with autogen.sh anymore
autoreconf -fi
./configure  --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"

