#!/bin/sh

get_version()
{
    (
        cd $1 > /dev/null
        VERSION=1:$(git describe --tags --always | sed -e 's/^[^0-9]*//' -e 's/\^0$//')
        if [ "$VERSION" = "1:" ]; then
            TIMESTAMP=$(git log -1 --date=short --format=%cd | sed 's/-/./g')
            COMMIT=$(git rev-parse --short HEAD)
            VERSION="2:${TIMESTAMP}.${COMMIT}"
        fi
        echo ${VERSION}
    )
}

do_subst() {
    sed  -e "0,/^mpv (.*)/s/(.*)/($1)/" \
         -e "s/^  \* local build.*/  \* local build with ffmpeg $2, libass $3, libmysofa $4, libarchive $5, avisynth $6, libplacebo $7, shaderc $8, freetype2 $9, fribidi $10, harfbuzz $11/" \
         -e"s/\(^ -- Local User <localuser@localhost>\).*/\1  $(date -R)/" debian/changelog.TEMPLATE > debian/changelog
}

do_subst $(get_version mpv) $(get_version ffmpeg) $(get_version libass) $(get_version libmysofa) $(get_version libarchive) $(get_version avisynth) $(get_version libplacebo) $(get_version shaderc) $(get_version freetype2) $(get_version fribidi) $(get_version harfbuzz)
