#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/fribidi_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/fribidi_options) "$@"
    unset -v IFS
fi

OPTIONS="-Dprefix="$BUILD/build_libs" -Dlibdir="$BUILD/build_libs/lib" -Dbuildtype=release -Ddefault_library=static -Ddocs=false"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

echo Using fribidi options: $OPTIONS "$@"

cd "$BUILD"/fribidi

meson setup build $OPTIONS "$@"
